name: firstapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # auto_route: ^10.2.0
  provider: ^6.1.5+1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  dartz: ^0.10.1
  get_storage: ^2.1.1
  # freezed_annotation: ^3.1.0
  # freezed: ^3.2.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/